### ISSUE TITLE
Postgres pod is failing

### ISSUE THREAD

**Issue by tselishev-semen** [mmumshad/kubernetes-example-voting-app#1]
Thank you for such a great overview of the k8s functionality, but I encountered an issue related to postgres-pod. The current configuration doesn't work on the latest GCP
```yml
// postgres-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      ports:
        - containerPort: 5432

```
It generates an error while pod is starting by executing a command `kubectl create -f postgres-pod.yml`:
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".
       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       
```

I fixed it this way:
```yml
// postgres-pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
      ports:
        - containerPort: 5432
```

It would be really cool if you can upgrade the repo with the working example

**Comment by rokair** [comment]
Tselishev Semen, I was having the same issues so thank you for posting the working example code.

**Comment by vikramshinde12** [comment]
Thanks @tselishev-semen, I also faced similar issue.

**Comment by ehernandez-xk** [comment]
@tselishev-semen @rokair @vikramshinde12 
Hello guys, I think the error is giving you advice on what to do to fix it.

I did it and now is working. I can create the PR if you allow me to do it.

To fix it:

Because this is an Example you can add the envVar POSTGRES_HOST_AUTH_METHOD=trust in the postgres-pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    ports:
     - containerPort: 5432
    env:
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
```

now create the pod.

Let me know if this fixes the issue, so I can create the PR
